### PUSH TO S3 ###
push_to_aws:
  stage: push
  needs:
    - run_build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .env
      - node_modules
      - dist
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws deploy push --application-name ${AWS_APP_NAME} --s3-location s3://${AWS_BUCKET_NAME}/${CI_COMMIT_TAG}.zip
  only:
    - master
    - /^v.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:0|[a-z]*)$/
  except:
    - branches

### DEPLOY TO EC2 ###
deploy_to_aws:
  stage: deploy
  needs:
    - push_to_aws
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws deploy create-deployment --application-name ${AWS_APP_NAME} --deployment-group-name ${AWS_DEPLOYMENT_GROUP} --s3-location bucket=${AWS_BUCKET_NAME},bundleType=zip,key=${CI_COMMIT_TAG}.zip
  only:
    - master
    - /^v.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:0|[a-z]*)$/
  except:
    - branches
